### PR TITLE
Added One Useful Resource

### PR DESCRIPTION
**Pull request by arjunkumar09**
Have Added One Useful Resource Under the Other Resources Section.

### CODE REVIEW

**Review by MTrajK — CHANGES_REQUESTED** [review]
I can see that you're also working for interviewbit. Your colleague (@letscode-17 Sonia M) has already opened a PR about this resource and I requested changes (but no changes for more than 17 days). See this PR and decide in which section this resource belongs (it can not belongs in 3 sections).
https://github.com/MTrajK/coding-problems/pull/20

**Comment by arjunkumar09** [comment]
> 
You can add this link in "Other Resources" section. The added link provides the best courses list of data structure and algorithm/.

**Comment by MTrajK** [comment]
> > 
> 
> You can add this link in "Other Resources" section. The added link provides the best courses list of data structure and algorithm/.

I can not see those changes in this PR, please update this PR with those changes (as you mean) and I'll review it and approve it.

**Comment by MTrajK** [comment]
@arjunkumar09 no feedback and action, I'm closing this PR (the behavior looks the same as the previous PR from your company).

**Pull request closed without merging**
